on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 14]
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Fetch all tags"
        run: "git fetch origin +refs/tags/*:refs/tags/*"
      - name: "Setup Java ${{ matrix.java }}"
        uses: "actions/setup-java@v1"
        with:
          java-version: ${{ matrix.java }}
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Cache Gradle wrapper"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/wrapper"
          key: "gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle welcome message"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/notifications"
          key: "gradle-notifications-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle dependencies"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/caches"
          key: "gradle-caches-${{ runner.os }}-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}"
      - name: "Gradle check"
        run: "./gradlew check --continue"
